#spring:
#datasource:
#driver-class-name: com.mysql.jdbc.Driver
#url: jdbc:mysql://localhost:3306/testone?useUnicode=true&characterEncoding=UTF-8
#username: root
#password: caopu1212



#禁用缓存
#spring:
#  thymeleaf:
#    cache: false
#
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

#
#mvc:
#static-path-pattern: /static/**    #静态资源的请求方式
#resources:
#
#spring.mvc.static-path-pattern: /static/**

spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #关闭缓存
